export const blogs =[
    {id:1,title:"How one Webflow user grew his single person consultancy from $0-100K in 14 months",description:"See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract",date:"19 Jan 2022",img:"/arabic-businessman-standing-on-street-and-using-laptop-9623794.png"},
    {id:2,title:"How one Webflow user grew his single person consultancy from $0-100K in 14 months",description:"See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract",date:"19 Jan 2022",img:"/woman-in-white-sleeveless-shirt-using-macbook-air-on-brown-wooden-table-3766189.png"},
    {id:3,title:"How one Webflow user grew his single person consultancy from $0-100K in 14 months",description:"See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract",date:"19 Jan 2022",img:"/apple-monitors-326518.png"},
    {id:4,title:"How one Webflow user grew his single person consultancy from $0-100K in 14 months",description:"See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract",date:"19 Jan 2022",img:"/photo-of-people-using-laptops-3182833.png"},
    {id:5,title:"How one Webflow user grew his single person consultancy from $0-100K in 14 months",description:"See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract",date:"19 Jan 2022",img:"/side-view-photo-of-smiling-woman-in-a-black-and-white-striped-top-sitting-on-a-bed-while-using-a-laptop-3765035.png"},
    {id:6,title:"How one Webflow user grew his single person consultancy from $0-100K in 14 months",description:"See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract",date:"19 Jan 2022",img:"/top-view-photo-of-person-holding-earphones-3183198.png"},
    {id:7,title:"How one Webflow user grew his single person consultancy from $0-100K in 14 months",description:"See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract",date:"19 Jan 2022",img:"/top-view-photo-of-people-having-a-meeting-3182822.png"},
    {id:8,title:"How one Webflow user grew his single person consultancy from $0-100K in 14 months",description:"See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract",date:"19 Jan 2022",img:"/man-wearing-red-crew-neck-shirt-1125028.png"},
    {id:9,title:"How one Webflow user grew his single person consultancy from $0-100K in 14 months",description:"See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract",date:"19 Jan 2022",img:"/group-of-person-sitting-indoors-3184306.png"},
]